// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "dev@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/example/weather": {
            "get": {
                "description": "Get current weather data from Open-Meteo for given coordinates",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "weather"
                ],
                "summary": "Get current weather",
                "parameters": [
                    {
                        "type": "number",
                        "description": "Latitude (-90 to 90)",
                        "name": "latitude",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Longitude (-180 to 180)",
                        "name": "longitude",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Include current weather (default: true)",
                        "name": "current_weather",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/simple-arq-golang_cmd_api_domains_exampleweather.WeatherResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/simple-arq-golang_cmd_api_domains_apierror.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/simple-arq-golang_cmd_api_domains_apierror.APIError"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Returns pong if the server is running",
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "pong",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user": {
            "post": {
                "description": "Create a new user with name and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/simple-arq-golang_cmd_api_domains_user.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/simple-arq-golang_cmd_api_domains_user.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/simple-arq-golang_cmd_api_domains_apierror.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/simple-arq-golang_cmd_api_domains_apierror.APIError"
                        }
                    }
                }
            }
        },
        "/user/{user_id}": {
            "get": {
                "description": "Retrieve a user by their unique ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/simple-arq-golang_cmd_api_domains_user.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/simple-arq-golang_cmd_api_domains_apierror.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/simple-arq-golang_cmd_api_domains_apierror.APIError"
                        }
                    }
                }
            }
        },
        "/user/{user_id}/weather": {
            "get": {
                "description": "Get a user by ID and combine with current weather at given coordinates",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users",
                    "weather"
                ],
                "summary": "Get user with weather data",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Latitude (-90 to 90)",
                        "name": "latitude",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Longitude (-180 to 180)",
                        "name": "longitude",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/simple-arq-golang_cmd_api_delegates.UserWithWeatherResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/simple-arq-golang_cmd_api_domains_apierror.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/simple-arq-golang_cmd_api_domains_apierror.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "simple-arq-golang_cmd_api_delegates.UserWithWeatherResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/simple-arq-golang_cmd_api_domains_user.User"
                },
                "weather": {
                    "$ref": "#/definitions/simple-arq-golang_cmd_api_domains_exampleweather.WeatherResponse"
                }
            }
        },
        "simple-arq-golang_cmd_api_domains_apierror.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                }
            }
        },
        "simple-arq-golang_cmd_api_domains_exampleweather.CurrentWeather": {
            "type": "object",
            "properties": {
                "interval": {
                    "type": "integer"
                },
                "is_day": {
                    "type": "integer"
                },
                "temperature": {
                    "type": "number"
                },
                "time": {
                    "type": "string"
                },
                "weathercode": {
                    "type": "integer"
                },
                "winddirection": {
                    "type": "integer"
                },
                "windspeed": {
                    "type": "number"
                }
            }
        },
        "simple-arq-golang_cmd_api_domains_exampleweather.WeatherResponse": {
            "type": "object",
            "properties": {
                "current_weather": {
                    "$ref": "#/definitions/simple-arq-golang_cmd_api_domains_exampleweather.CurrentWeather"
                },
                "elevation": {
                    "type": "number"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                }
            }
        },
        "simple-arq-golang_cmd_api_domains_user.CreateUserRequest": {
            "type": "object",
            "required": [
                "name",
                "password"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "simple-arq-golang_cmd_api_domains_user.User": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Simple Arq Golang API",
	Description:      "Base scaffolding for Go APIs with Gin framework",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
